# OpenWrt SDK build targets.
# The SDK is looked up using `target` and `subtarget`.
# `architecture` is added to package build metadata as it's needed for package releases.
# `codenames` represent Wayru compatibility. These are added for documentation purposes.

[[builds]]
target = "ath79"
subtarget = "generic"
architecture = "mips_24kc"
codenames = [
    "genesis",
    "odyssey",
    "zeus",
    "ares",
    "kratos",
    "hemera",
    "atenea",
    "artemisa",
    "deimos",
]

[[builds]]
target = "ramips"
subtarget = "mt7621"
architecture = "mipsel_24kc"
codenames = ["aria", "apollo", "chronos"]

[[builds]]
target = "ipq40xx"
subtarget = "mikrotik"
architecture = "arm_cortex-a7_neon_vfpv4"
codenames = ["loki", "gaia", "helios"]

[[builds]]
target = "mediatek"
subtarget = "mt7622"
architecture = "aarch64_cortex-a53"
codenames = ["neron"]

[[builds]]
target = "mediatek"
subtarget = "filogic"
architecture = "aarch64_cortex-a53"
codenames = ["apocalypse", "prometheus", "eclypse"]
