# OpenWrt SDK build targets.
# The SDK is looked up using `target` and `subtarget`.
# `architecture` is added to package build metadata as it's needed for package releases.
# `codenames` represent Fry device compatibility. These are added for documentation purposes.

[[builds]]
target = "ath79"
subtarget = "generic"
architecture = "mips_24kc"
codenames = [
    "genesis",
    "odyssey",
    "zeus",
    "ares",
    "kratos",
    "hemera",
    "atenea",
    "artemisa",
    "deimos",
]
version = "23.05.5"
feedsName = "fry_custom"

[[builds]]
target = "ramips"
subtarget = "mt7621"
architecture = "mipsel_24kc"
codenames = ["aria", "apollo", "chronos"]
version = "23.05.5"
feedsName = "fry_custom"

[[builds]]
target = "ipq40xx"
subtarget = "mikrotik"
architecture = "arm_cortex-a7_neon-vfpv4"
codenames = ["loki", "gaia", "helios"]
version = "23.05.5"
feedsName = "fry_custom"

[[builds]]
target = "mediatek"
subtarget = "mt7622"
architecture = "aarch64_cortex-a53"
codenames = ["neron"]
version = "23.05.5"
feedsName = "fry_custom"

[[builds]]
target = "mediatek"
subtarget = "filogic"
architecture = "aarch64_cortex-a53"
codenames = ["apocalypse", "prometheus", "eclypse"]
version = "23.05.5"
feedsName = "fry_custom"
